### ISSUE TITLE
Mudul Crash

### ISSUE THREAD

**Issue by btro1404** [skuethe/MMM-HH-LocalTransport#2]
Das Modul stürzt ab, wenn keine Abfahrtzeiten (mehr) gefunden werden - z.B. beim Beginn der Betriebspause. Die Anzeige bleibt dann mit nur einer Zeile bei der letzten Abfahrt und der Zeit "Now" hängen bis der MagicMirror neu gestartet wird.

**Comment by skuethe** [comment]
Kann ich mit meinem Setup aktuell nicht nachstellen - da funktioniert alles.
Um das näher analysieren zu können benötige ich also mehr Informationen (z.B. die `id` mit welcher dies auftritt und am Besten noch eine Uhrzeit).

**Comment by btro1404** [comment]
Bei mir ist das Modul (auch -  aber nicht nur - als einzige Instanz von MMM-HH-LocalTransport) nachts regelmäßig abgestürzt. Ich nutze:

```
module: 'MMM-HH-LocalTransport',
position: 'top_left',
header: 'HVV - Schillerstraße',
config: {
    id: 'Master:36034', 
    apiKey: 'xxxx',
    apiUser: 'yyyy',
    maximumEntries: 8, 
    maxTimeOffset: 200,
    initialLoadDelay: 1, 
    updateInterval: 1 * 60 * 1000 
}
```
Über die Uhrzeit kann ich leider nichts sagen, denn es werden ja nur relative Zeiten angezeigt. Abends geht es noch, morgens ist dann nur die eine "Now"-Zeile in der Anzeige. Bei den anderen Modulen habe ich morgens keine Probleme festgestellt.

**Comment by btro1404** [comment]
Ist das Problem dadurch nachvollziehbar?

**Comment by skuethe** [comment]
Ich habe noch keine Zeit gefunden das zu debuggen. Vor allem weil sich die Fehlersuche ja nicht direkt nachstellen lässt. Ich muss also den code durchgehen und versuchen die Ursache irgendwie zu finden. Hat bei mir aktuell nicht die höchste Priorität, sorry.

**Comment by btro1404** [comment]
Klar, kein Problem.

Ich kann mit Einträgen in der `/home/pi/.pm2/logs/mm-error.log` nicht wirklich etwas anfangen, aber hilft dir das evtl?
```
[2021-03-18 23:49:49.919] [ERROR]  Whoops! There was an uncaught exception...
[2021-03-18 23:49:49.923] [ERROR]  TypeError: Cannot read property 'length' of undefined
    at Class.processTrains (/home/pi/MagicMirror/modules/MMM-HH-LocalTransport/node_helper.js:120:49)
    at /home/pi/MagicMirror/modules/MMM-HH-LocalTransport/node_helper.js:100:30
    at Request.handleRequestResponse [as _callback] (/home/pi/MagicMirror/modules/MMM-HH-LocalTransport/node_modules/unirest/index.js:552:70)
    at Request.self.callback (/home/pi/MagicMirror/modules/MMM-HH-LocalTransport/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-HH-LocalTransport/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-HH-LocalTransport/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
[2021-03-18 23:49:49.952] [ERROR]  MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[2021-03-18 23:49:49.955] [ERROR]  If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
```

**Comment by skuethe** [comment]
Logisch hilft das :) so etwas immer gerne direkt mitsenden.

**Comment by skuethe** [comment]
Ich hab mal einen schnellen fix im development branch commited. Auf die Schnelle sollte es das schon beheben, bitte einmal testen. Dazu:

1. in den Modul-Ordner wechseln:
  ```bash
  ~ $ cd MagicMirror/modules/MMM-HH-LocalTransport/
  ```
2. Die vorhandenen branches aktualisieren und auf den `development` branch wechseln:
  ```bash
  ~/MagicMirror/modules/MMM-HH-LocalTransport $ git fetch
  [...]
  ~/MagicMirror/modules/MMM-HH-LocalTransport $ git checkout development
  [...]
  ```
3. Magic Mirror Dienst durchstarten
  ```bash
  ~/MagicMirror/modules/MMM-HH-LocalTransport $ sudo systemctl restart magicmirror.service
  ```

**Comment by btro1404** [comment]
Das Problem ist mit diesem Patch seit einigen Tagen nicht mehr aufgetreten. Vielen Dank!

**Comment by skuethe** [comment]
Ich habe die Änderungen nun in den master branch übernommen. Bitte nicht vergessen wieder auf diesen zurück zu wechseln:

```bash
~ $ cd MagicMirror/modules/MMM-HH-LocalTransport/
~/MagicMirror/modules/MMM-HH-LocalTransport $ git checkout master
[...]
~/MagicMirror/modules/MMM-HH-LocalTransport $ git pull
[...]
```
